### PR TITLE
Add parameter to specify custom traefik routing rule

### PR DESCRIPTION
**Pull request by jacksgt**

### CODE REVIEW

**Comment by jacksgt** [comment]
@martialblog Do you think it makes sense like this? Or should we just do the following:

```puppet
if $::applicationtier == 'staging' {
  $rule = "abc"
} else {
  $rule = "xyz"
}
```

**Comment by martialblog** [comment]
@jacksgt I like the solution in the commit

**Review by martialblog — APPROVED** [review]
Looks sensible

**Comment by jacksgt** [comment]
Ok, thank you for the super quick answer. I will do the same for webshop then.

**Pull request merged**
